const data =  [
  {
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },{
    "firstName":"FirstName",
    "lastName":"LastName",
    "username":"Username",
    "email":"username@mail.com"
  },
]
  
  export default data;